# Logging configuration

version: 1
disable_existing_loggers: false

# Formatters
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '%(levelname)s - %(message)s'

# Handlers
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/research_assistant.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

# Loggers
loggers:
  research_assistant:
    level: DEBUG
    handlers: [console, file, error_file, debug_file]
    propagate: false
  
  research_assistant.search:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  research_assistant.extraction:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  research_assistant.analysis:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  research_assistant.llm:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  research_assistant.storage:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  research_assistant.tools:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  research_assistant.reports:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  research_assistant.utils:
    level: INFO
    handlers: [console, file]
    propagate: false

# Root logger
root:
  level: INFO
  handlers: [console, file]
  propagate: true

# Filter settings
filters:
  require_debug_true:
    (): logging_filters.RequireDebugTrue

# Logging levels
levels:
  CRITICAL: 50
  ERROR: 40
  WARNING: 30
  INFO: 20
  DEBUG: 10
  NOTSET: 0 