# Search engine configurations
search_engines:
  duckduckgo:
    enabled: true
    max_results: 10
    timeout: 30
  
  searx:
    enabled: false
    instances:
      - url: "https://searx.example.com"
        timeout: 30
  
  academic:
    arxiv:
      enabled: true
      max_results: 50
      categories:
        - cs.AI
        - cs.CL
        - cs.LG
    
    scholarly:
      enabled: true
      max_results: 20
      timeout: 60 